"""Report generation agent decoupled from Streamlit UI."""

from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

import pandas as pd

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    PageBreak, Image, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas

from matplotlib.backends.backend_agg import FigureCanvasAgg

from utils.config import REPORT_AUTHOR, REPORT_TITLE, REPORTS_DIR
from utils.session_manager import SessionManager


class ReportAgent:
    """Generate PDF reports leveraging session data."""

    def __init__(self, session: SessionManager):
        self.session = session
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Section header
        self.styles.add(ParagraphStyle(
            name='ReportSectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2ca02c'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        # Subsection
        self.styles.add(ParagraphStyle(
            name='ReportSubSection',
            parent=self.styles['Heading3'],
            fontSize=14,
            textColor=colors.HexColor('#ff7f0e'),
            spaceAfter=10,
            spaceBefore=10,
            fontName='Helvetica-Bold'
        ))
        
        # Body text
        self.styles.add(ParagraphStyle(
            name='ReportBodyText',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=8,
            alignment=TA_JUSTIFY
        ))
    
    def _create_header_footer(self, canvas_obj, doc):
        """Create header and footer for each page"""
        canvas_obj.saveState()
        
        # Header
        canvas_obj.setFont('Helvetica-Bold', 10)
        canvas_obj.drawString(inch, A4[1] - 0.5*inch, REPORT_TITLE)
        
        # Footer
        canvas_obj.setFont('Helvetica', 9)
        canvas_obj.drawString(inch, 0.5*inch, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        canvas_obj.drawRightString(A4[0] - inch, 0.5*inch, f"Page {doc.page}")
        
        canvas_obj.restoreState()
    
    def _create_title_section(self) -> list:
        """Create title section"""
        elements = []
        
        # Title
        title = Paragraph(REPORT_TITLE, self.styles['CustomReportTitle'])
        elements.append(title)
        elements.append(Spacer(1, 0.3*inch))
        
        # Metadata
        metadata_text = f"""
        <b>Generated By:</b> {REPORT_AUTHOR}<br/>
        <b>Date:</b> {datetime.now().strftime('%B %d, %Y')}<br/>
        <b>Time:</b> {datetime.now().strftime('%H:%M:%S')}<br/>
        """
        
        file_info = self.session.get_file_info()
        if file_info:
            metadata_text += f"""
            <b>Source File:</b> {file_info.get('filename', 'N/A')}<br/>
            <b>File Size:</b> {file_info.get('size_mb', 0):.2f} MB<br/>
            """
        
        metadata = Paragraph(metadata_text, self.styles['ReportBodyText'])
        elements.append(metadata)
        elements.append(Spacer(1, 0.5*inch))
        
        return elements
    
    def _create_dataset_overview(self, df: pd.DataFrame) -> list:
        """Create dataset overview section"""
        elements = []
        
        # Section header
        elements.append(Paragraph("1. Dataset Overview", self.styles['ReportSectionHeader']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Summary statistics
        summary_data = [
            ['Metric', 'Value'],
            ['Total Rows', f"{len(df):,}"],
            ['Total Columns', str(len(df.columns))],
            ['Memory Usage', f"{df.memory_usage(deep=True).sum() / (1024*1024):.2f} MB"],
            ['Missing Values', str(df.isnull().sum().sum())],
            ['Duplicate Rows', str(df.duplicated().sum())]
        ]
        
        table = Table(summary_data, colWidths=[3*inch, 3*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f77b4')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Column information
        elements.append(Paragraph("Column Details", self.styles['ReportSubSection']))
        
        col_data = [['Column Name', 'Data Type', 'Non-Null', 'Unique']]
        for col in df.columns[:15]:  # Limit to first 15 columns
            col_data.append([
                col,
                str(df[col].dtype),
                str(df[col].count()),
                str(df[col].nunique())
            ])
        
        if len(df.columns) > 15:
            col_data.append(['...', '...', '...', '...'])
        
        col_table = Table(col_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        col_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2ca02c')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        
        elements.append(col_table)
        elements.append(Spacer(1, 0.3*inch))
        
        return elements
    
    def _create_cleaning_summary(self) -> list:
        """Create cleaning operations summary"""
        elements = []
        
        elements.append(Paragraph("2. Data Cleaning Summary", self.styles['ReportSectionHeader']))
        elements.append(Spacer(1, 0.2*inch))
        
        if not self.session.state.cleaning_log:
            elements.append(Paragraph("No cleaning operations performed.", self.styles['ReportBodyText']))
            elements.append(Spacer(1, 0.3*inch))
            return elements
        
        # Create cleaning log table
        log_data = [['#', 'Timestamp', 'Action', 'Details']]
        
        for i, log in enumerate(self.session.state.cleaning_log, 1):
            log_data.append([
                str(i),
                log['timestamp'],
                log['action'],
                log['details']
            ])
        
        log_table = Table(log_data, colWidths=[0.5*inch, 1.5*inch, 1.5*inch, 3*inch])
        log_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ff7f0e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.lightgoldenrodyellow),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        
        elements.append(log_table)
        elements.append(Spacer(1, 0.3*inch))
        
        return elements
    
    def _create_query_history(self) -> list:
        """Create query history section"""
        elements = []
        
        elements.append(Paragraph("3. Query History & Results", self.styles['ReportSectionHeader']))
        elements.append(Spacer(1, 0.2*inch))
        
        if not self.session.state.query_history:
            elements.append(Paragraph("No queries executed.", self.styles['ReportBodyText']))
            elements.append(Spacer(1, 0.3*inch))
            return elements
        
        for i, query_info in enumerate(self.session.state.query_history, 1):
            # Query header
            query_header = Paragraph(f"Query {i}: {query_info['query']}", self.styles['ReportSubSection'])
            elements.append(query_header)
            
            # Timestamp and explanation
            details = f"<b>Executed:</b> {query_info['timestamp']}<br/>"
            details += f"<b>Explanation:</b> {query_info['explanation']}<br/>"
            
            # Result
            result = query_info['result']
            if isinstance(result, (int, float)):
                details += f"<b>Result:</b> {result:,}"
            elif isinstance(result, (pd.DataFrame, pd.Series)):
                details += f"<b>Result:</b> Returned {len(result)} rows/values"
            else:
                details += f"<b>Result:</b> {str(result)[:100]}"
            
            elements.append(Paragraph(details, self.styles['ReportBodyText']))
            elements.append(Spacer(1, 0.2*inch))
        
        return elements
    
    def _create_visualizations(self) -> list:
        """Create visualizations section"""
        elements = []
        
        elements.append(PageBreak())
        elements.append(Paragraph("4. Visualizations", self.styles['ReportSectionHeader']))
        elements.append(Spacer(1, 0.2*inch))
        
        if not self.session.state.generated_charts:
            elements.append(Paragraph("No charts generated.", self.styles['ReportBodyText']))
            return elements
        
        for i, chart_info in enumerate(self.session.state.generated_charts, 1):
            # Chart title
            chart_title = Paragraph(f"Chart {i}: {chart_info['title']}", self.styles['ReportSubSection'])
            elements.append(chart_title)
            elements.append(Spacer(1, 0.1*inch))
            
            # Save matplotlib figure to bytes
            try:
                chart_obj = chart_info.get('chart')
                if chart_obj is None:
                    raise ValueError('Chart object not available')

                img_buffer = io.BytesIO()
                FigureCanvasAgg(chart_obj).print_png(img_buffer)
                img_buffer.seek(0)

                # Add image to PDF
                img = Image(img_buffer, width=5*inch, height=3.5*inch)
                elements.append(img)
                elements.append(Spacer(1, 0.3*inch))
            except Exception as e:
                elements.append(Paragraph(f"Error rendering chart: {str(e)}", self.styles['ReportBodyText']))
        
        return elements
    
    def _create_insights_summary(self) -> list:
        """Create insights summary section"""
        elements = []
        
        elements.append(PageBreak())
        elements.append(Paragraph("5. Key Insights", self.styles['ReportSectionHeader']))
        elements.append(Spacer(1, 0.2*inch))
        
        if not self.session.state.insights:
            elements.append(Paragraph("No insights generated.", self.styles['ReportBodyText']))
            return elements
        
        for i, insight in enumerate(self.session.state.insights, 1):
            insight_text = f"{i}. {insight['text']}"
            elements.append(Paragraph(insight_text, self.styles['ReportBodyText']))
            elements.append(Spacer(1, 0.1*inch))
        
        return elements
    
    def generate_report(self, filename: str = None) -> str:
        """
        Generate complete PDF report
        
        Args:
            filename: Output filename (optional)
            
        Returns:
            Path to generated PDF
        """
        if filename is None:
            filename = f"analysis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        output_path = REPORTS_DIR / filename
        
        # Create PDF document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        # Build content
        elements = []
        
        # Add all sections
        elements.extend(self._create_title_section())
        
        df = self.session.get_dataframe('current')
        if df is not None:
            elements.extend(self._create_dataset_overview(df))
        
        elements.extend(self._create_cleaning_summary())
        elements.extend(self._create_query_history())
        elements.extend(self._create_visualizations())
        elements.extend(self._create_insights_summary())
        
        # Build PDF
        doc.build(elements, onFirstPage=self._create_header_footer, onLaterPages=self._create_header_footer)
        
        return str(output_path)
    
    def execute(self) -> Dict[str, Any]:
        summary = self.session.get_summary()

        if not summary['has_data']:
            return {'success': False, 'message': 'No data available for report generation.'}

        pdf_path = self.generate_report()
        return {
            'success': True,
            'report_path': pdf_path,
            'summary': summary
        }
